version: '3'

services:
  #CloudBees Jenkins Enterprise Master
  #https://hub.docker.com/r/cloudbees/jenkins-enterprise/
  cje:
     build:
        context: .
     environment:
        JENKINS_SLAVE_AGENT_PORT: "50000"
        JAVA_OPTS: "-Dorg.apache.commons.jelly.tags.fmt.timeZone=America/New_York"
     ports:
        - "9070:8080" #host:container
     volumes:
        - /Users/craigvitter/JenkinsEnterprise:/var/jenkins_home     # Set the Jenkins home on the host machine
        - /var/run/docker.sock:/var/run/docker.sock            # Allow the container to run Docker on Docker
